### ISSUE TITLE
How to install php-cephclient in xampp in window 10

### ISSUE THREAD

**Issue by vinodhoney** [octivi/php-cephclient#2]
Hello,
How to install php-cephclient in xampp in window 10
https://github.com/octivi/php-cephclient

On run command php composer.phar require src/octivi/CephClient:*
Getting error
# php composer.phar require src/octivi/CephClient:*
./composer.json has been updated
Loading composer repositories with package information
Updating dependencies (including require-dev)
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - The requested package src/octivi/cephclient could not be found in any version, there may be a typo in the package name.

Potential causes:
 - A typo in the package name
 - The package is not available in a stable-enough version according to your minimum-stability setting
   see <https://getcomposer.org/doc/04-schema.md#minimum-stability> for more details.

Read <https://getcomposer.org/doc/articles/troubleshooting.md> for further common problems.

Installation failed, reverting ./composer.json to its original content.

Do let me know, how to install.

How to install php-cephclient in xampp in window 10

**Comment by vardius** [comment]
@vinodhoney please use package name when installing with **require**

Run
```
composer require octivi/php-cephclient
```
or composer is not installed globally
```
php composer.phar  octivi/php-cephclient
```

You can specify version as `*` wildcard or directly `dev-master`.

```
composer require octivi/php-cephclient:*
```

```
composer require octivi/php-cephclient:dev-master
```

**Comment by vinodhoney** [comment]
Thank you Vardius for quick response!

Still i am unable to install the packege

From C:\composer

composer require Octivi/CephClient:*
composer require Octivi/CephClient:dev-master
Package taken from
https://github.com/octivi/php-cephclient/
Download and run Composer-Setup.exe 
https://getcomposer.org/download/

From C:\xampp\htdocs\drupal\sites\all\libraries\PHP-API-Wrapper\composer.phar

php composer.phar  Octivi/CephClient:*
php composer.phar  Octivi/CephClient:dev-master
<img width="960" alt="php-cephclient-install-error-1" src="https://user-images.githubusercontent.com/37368694/37449477-5475c068-2850-11e8-8438-1586c3ae308c.png">
 
Thanks in advance!
